HaikuArchives/ArtPaint

- addons/AddOns/Working/WaveAddOn/Wave.h
- artpaint/controls/ColorPalette.cpp
- artpaint/controls/ColorView.cpp
- artpaint/controls/VisualColorControl.cpp
- artpaint/paintwindow/StatusView.cpp
- artpaint/windows/BrushStoreWindow.cpp
- build.sh
* have build.sh exit on failure.
* use build.sh parameters as parameters for make
> x86_64 build fix.

- artpaint/paintwindow/PaintWindow.cpp
- artpaint/paintwindow/StatusView.cpp
- artpaint/paintwindow/StatusView.h
> convert Empty Paint Window to the layout API

- artpaint/windows/GlobalSetupWindow.cpp
> Remove country flags in Window->Settings->Language tab.

- addons/AddOns/Working/AntiDitherer/AntiDitherer.cpp
- addons/AddOns/Working/AntiDitherer/AntiDitherer.h
- addons/AddOns/Working/AntiDitherer/Makefile
Set minimal block size to "1". A block size of "0" makes no sense...
Fixes #94
> Anti-Dither: Use a BSpinner

- artpaint/Utilities/BitmapUtilities.cpp
- artpaint/Utilities/BitmapUtilities.h
- artpaint/tools/AirBrushTool.cpp
- artpaint/tools/BitmapDrawer.cpp
- artpaint/tools/Brush.cpp
- artpaint/tools/BrushTool.cpp
- artpaint/tools/ColorSelectorTool.cpp
- artpaint/tools/CoordinateQueue.cpp
- artpaint/tools/CoordinateReader.cpp
- artpaint/tools/FillTool.cpp
- artpaint/tools/SelectorTool.cpp
- artpaint/tools/ToolEventAdapter.cpp
- artpaint/tools/ToolScript.cpp
Fixed the coding style in multiple files as per the Guidelines, mostly the function descriptions.
> Fixed a few coding style issues

- locales/fi.catkeys
I guess I hadn't tested the Finnish catkeys, and it turns out they were broken.  Here's a fixed version.
> Localization: Fix broken Finnish catkeys

- artpaint/tools/FillTool.cpp
Added LayoutChanged() handler to update gradient preview in tool window for Fill tool. 
Fixes #119
> Fill gradient redraw

- artpaint/paintwindow/PaintWindow.cpp
Store the add-ons in a std::map using the localized name as the key.
std::map sorts alphabetically by default, yay - then just retrieve
them from the map again and add to the menu.
Fixes #164
> Add-ons: sort the addon names alphabetically by localized name

- artpaint/viewmanipulators/TextManipulator.cpp
> Text Alpha: set alpha blending modes so that text renders correctly

- artpaint/tools/SelectorTool.cpp
Make new BMessage so Intelligent Scissors mode functions again
Fixes #199
> Selection: Intelligent scissors BMessage is getting overwritten by Magic wand

- addons/AddOns/ColorReducer/palette_generator.cpp
- addons/UtilityClasses/ImageProcessingLibrary.cpp
- artpaint/application/HSPolygon.cpp
- artpaint/controls/ColorPalette.cpp
- artpaint/layers/Layer.cpp
- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/ImageView.cpp
- artpaint/tools/AirBrushTool.cpp
- artpaint/tools/BrushTool.cpp
- artpaint/tools/EraserTool.cpp
- artpaint/tools/FreeLineTool.cpp
This is related to #124 but I haven't gone through the whole report. 
Fixed a number of memory leaks that I added when I fixed the alpha drawing. :/   I am secretly hoping #212 is related to the memory leak as I was painting just fine for a while and then it crashed without warning.
> Clang static analysis: Fixed several memory leaks and dead initializations

- addons/UtilityClasses/ImageProcessingLibrary.cpp
- artpaint/tools/BrushTool.cpp
- artpaint/tools/FreeLineTool.cpp
- artpaint/tools/StraightLineTool.cpp
- artpaint/viewmanipulators/CropManipulator.cpp
- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/TranslationManipulator.cpp
Some code cleanup, memory leak prevention, and unused assignments to address some items in #124
> More static analysis fixes to prevent memory leaks and dead assignments

- addons/AddOns/Blur/Blur.cpp
- addons/AddOns/ColorBalance/ColorBalance.cpp
- addons/AddOns/ColorReducer/Reducer.cpp
- addons/AddOns/ColorReducer/color_mapper.cpp
- addons/AddOns/Emboss/EmbossAddOn.cpp
- addons/AddOns/Grayscale/GrayscaleAddOn.cpp
- addons/AddOns/Halftone/Halftone.cpp
- addons/AddOns/Interference/Interference.cpp
- addons/AddOns/MarbleTexturer/Marble.cpp
- addons/AddOns/Oil/OilAddOn.cpp
- addons/AddOns/Threshold/Threshold.cpp
- addons/AddOns/Twirl/Twirl.cpp
- addons/AddOns/Wave/Wave.cpp
Removed dead initializations, potential memory leaks, and other items from the 6-26-2022 report
Partially addresses #124
> Clang static analysis: cleaned up potential memory leaks etc.

- artpaint/paintwindow/Image.cpp
When the user has no settings for the alpha bg, the canvas may appear black.  This change sets the alpha for the default colors so that the bg renders correctly.
> Image: set default alpha for bg when there are no settings

- Makefile
- artpaint/application/CustomGridLayout.cpp
- artpaint/application/CustomGridLayout.h
- artpaint/application/MessageConstants.h
- artpaint/layers/Layer.cpp
- artpaint/layers/LayerView.cpp
- artpaint/layers/LayerView.h
- artpaint/layers/LayerWindow.cpp
- artpaint/layers/LayerWindow.h
- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/ImageView.cpp
- locales/en.catkeys
I moved the layer operations up to the top and out of each layer, and added a transparency slider so you can adjust layer transparency easily. Also re-enabled(?) the layer name field and moved visibility to the left.  This is more like how Photoshop's layer panel is. 
oh and the changes to the rendering are in preparation for adding the ability to change to different compositing modes for the layers. 
However, the layouting is giving me headaches.  I'm positing this mostly for comments or suggestions - it's not done but wanted to get thoughts. 
Related to #109
> Layers window updates

- artpaint/application/MessageConstants.h
- artpaint/application/PixelOperations.h
- artpaint/layers/Layer.cpp
- artpaint/layers/Layer.h
- artpaint/layers/LayerWindow.cpp
- artpaint/layers/LayerWindow.h
- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/PaintWindow.cpp
- artpaint/paintwindow/PaintWindow.h
- locales/en.catkeys
- Added color blend modes to Layers, very similar to Photoshop blending
modes:
Normal, Multiply. Divide, Screen, Overlay, Hard light, Soft light,
Vivid light, Pin light, Hard mix, Difference, Exclusion,
Color dodge, Linear dodge, Color burn, Linear burn,
Darken, and Lighten
- Blend mode is "applied" when merging layers, as is transparency.
> Layers: Added color blend modes

- artpaint/layers/LayerWindow.cpp
> LayerWindow: set default for dropdown to "Normal"

- artpaint/tools/StraightLineTool.cpp
- artpaint/tools/StraightLineTool.h
> Straight Line: disable size slider if "Adjustable width" is checked

- artpaint/paintwindow/MagnificationView.cpp
- artpaint/paintwindow/StatusView.cpp
> StatusView: main color wells and mag buttons resize based on font size

- artpaint/controls/ColorPalette.cpp
- artpaint/controls/ColorSlider.cpp
- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/ImageView.cpp
- artpaint/tools/FillTool.cpp
- artpaint/viewmanipulators/RotationManipulator.cpp
> Clang static analysis: Cleaned up various potential issues

- artpaint/tools/SelectorTool.cpp
Ok, intelligent scissors should have way fewer artifacts now. 
I feel like I said this before... :laughing: 
Fixes #6
> Intelligent scissors artifacts

- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/Image.h
- artpaint/paintwindow/PaintWindow.cpp
save active layer index as file attribute and read when reopening project
Fixes #233
> Image: save active layer index and restore on project load

- artpaint/Utilities/BitmapUtilities.cpp
- artpaint/tools/SelectorTool.cpp
- artpaint/tools/SelectorTool.h
> Selector tool: add Ellipse option

- artpaint/paintwindow/ImageView.cpp
Nothing but code cleanup.  Tried to make the code more standard and Haiku-like.
> ImageView: code cleanup

- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/ImageView.h
If you hold SPACE, drag to pan, then release the mouse button but keep holding SPACE, clicking again to pan doesn't always work.  Releasing SPACE and pressing it again works.  
I discovered that WonderBrush has exactly the same problem - not sure if it's a Haiku issue or my setup? 
Fixes #98
> ImageView: add panning if the user holds down the space bar

- artpaint/application/Selection.cpp
only clear selection if BOTH are true.
Fixes #300
> Selection: don't clear selection if either all points are included or excluded

- artpaint/tools/BrushEditor.cpp
- artpaint/tools/ColorSelectorTool.cpp
- artpaint/viewmanipulators/CropManipulator.cpp
- artpaint/viewmanipulators/FreeTransformManipulator.cpp
- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/ScaleManipulator.cpp
- artpaint/viewmanipulators/TextManipulator.cpp
- artpaint/viewmanipulators/TranslationManipulator.cpp
- locales/en.catkeys
* Added "Color picker window", it appears as window title in the Deskbar and should be translated, however short lived the pop-up window is.
* Updated help texts to fit better to the tools ones.
> Changed/added string, updated en.catkeys

- artpaint/paintwindow/Image.cpp
Coulda sworn I tested this a lot but apparently not... 
Fixes #313
> Image: make sure layer_index is LESS than layer count when selecting

- artpaint/tools/ColorSelectorTool.cpp
ran across a random crash where the value was out of bounds for the array.
> ColorSelectorTool: check if value is in range of sqrt table to avoid crashes

- artpaint/tools/SelectorTool.cpp
- artpaint/tools/SelectorTool.h
massively cleaned up and reduced the span-checking code...probably will do that for FillTool as well as I think it's almost the same code...
> SelectorTool: code cleanup and refactor of Check*Spans code.

- artpaint/application/UtilityClasses.cpp
- artpaint/application/UtilityClasses.h
- artpaint/tools/BrushEditor.cpp
- artpaint/tools/RectangleTool.cpp
- artpaint/tools/StraightLineTool.cpp
- also adjusted Rectangle angle snapping to 22.5 instead of 45 degrees per comment in #316 
- changed BrushEditor to use new snap code too
> Snapping: factored out snap code to UtilityClasses.

- artpaint/paintwindow/PaintWindow.cpp
> PaintWindow: Move selection items out to a top-level "Selection" menu

- artpaint/application/Selection.cpp
- artpaint/application/Selection.h
- artpaint/paintwindow/ImageView.cpp
- but changed "Dilatate" to "Dilate" because it bothered me
> Selection: code cleanup only, no functionality changed

- artpaint/paintwindow/ImageView.cpp
also:
- restored ALT for color picker
- reversed middle-mouse-button panning to match SPACE panning
Fixes #337 
Fixes #338 
Fixes #339
> UX tweaks: reverse mouse-wheel zoom, remove ALT from zoom, etc.

- artpaint/application/MessageConstants.h
- artpaint/application/Selection.cpp
- artpaint/application/Selection.h
- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/ImageView.h
- artpaint/paintwindow/PaintWindow.cpp
> Selection: add option to hide selection borders.

- artpaint/tools/SelectorTool.cpp
- artpaint/tools/SelectorTool.h
Otherwise the tolerance slider could be mistaken to be applied to other selection tools.
> Inset "Tolerance" slider to be under "Magic wand"

- artpaint/Utilities/BitmapUtilities.cpp
- artpaint/Utilities/BitmapUtilities.h
- artpaint/application/MessageConstants.h
- artpaint/application/Selection.h
- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/PaintWindow.cpp
Added option to select all non-transparent pixels in the current layer.  I called it "All pixels" in the menu but open to suggestions!
> Selection: add option to select all non-transparent pixels

- artpaint/application/HSPolygon.cpp
- artpaint/application/HSPolygon.h
- artpaint/application/Selection.cpp
- artpaint/application/Selection.h
- also added Contains() function to HSPolygon; not needed for this change but perhaps for future use.
- safety check for ContainsPoint() function to disallow negative x & y values
No functionality change, only code cleanup/refactor.
> Selection: refactored SimplifySelection to make it easier to follow

- artpaint/layers/LayerWindow.cpp
> LayerWindow: add message filter for B_KEY_DOWN to layer window

- artpaint/paintwindow/PaintWindow.cpp
Fixed all the mentioned issues as far as I can tell - it resizes to fit with full scrollbars, and doesn't end up in situations where the window is partially off the screen - if that's going to happen it centers the window. 
Also removed the menu item because it really does behave exactly the same as the widget on the window tab, so no need to waste a menu item. 
Fixes #322
> PaintWindow: fix bugs in resize-to-fit, and remove menu item

- artpaint/application/Selection.cpp
- artpaint/application/Selection.h
Ok, this was the correct fix after all, but I deleted some lines that I shouldn't have. 
Fixes #367
> Selection: draw selection_map on view before adding polygons

- artpaint/tools/TransparencyTool.cpp
> Transparency Tool: only affect selected areas unless there's no selection

- addons/AddOns/AntiDitherer/AntiDitherer.cpp
- use selection in Anti-Dither addon
- also refactored anti_dither function to remove nearly duplicate code
I couldn't help myself. 
Addresses #224
Still a few more addons to do for that ticket
> Anti-Dither addon: only affect selected areas if there's a selection

- artpaint/application/HSPolygon.cpp
- artpaint/application/HSPolygon.h
- artpaint/application/Selection.cpp
- artpaint/application/Selection.h
- artpaint/paintwindow/PaintWindow.cpp
- artpaint/viewmanipulators/FlipManipulator.cpp
> FlipManipulator: make horiz and vertical flip respect selections

- artpaint/Utilities/BitmapUtilities.cpp
- artpaint/application/Selection.cpp
Fixes #393 
This is even sillier than the one line change from #382...
> Ellipse selection: fix alpha for background when adding bitmap selection

- artpaint/paintwindow/ImageView.cpp
> ImageView: increment change counter when non-GUI manipulators are used

- artpaint/paintwindow/ImageView.cpp
I tried moving the space-panning code to whether there's a manipulator/addon active or not.  It seems to work although it's not totally perfect - like if you are translating and you click INSIDE the selection, it doesn't do anything.  If you click OUTSIDE the selection with space down it works. 
Same with addons, some addons might change the center of the effect when you click to pan but that might be unavoidable.  Overall it seems to function - give it a try? 
Fixes #351 
Fixes #389
> ImageView: allow space panning even when manipulator/addon is active

- artpaint/application/UndoQueue.h
- artpaint/paintwindow/ImageView.cpp
> ImageView: decrease change counter on undo. clear changes if no more undos

- artpaint/viewmanipulators/TranslationManipulator.cpp
Another try at this pesky ticket. 
Fixes #24 
Never give up hope!
> TranslationModifier: adjust "clear" rect to be larger to avoid artifacts

- artpaint/paintwindow/ImageView.cpp
oops indeed.  I think this change still allows space panning, but filters out everything else unless the window is active
Fixes #400
> ImageView: only capture keypresses when window is active (except space)

- artpaint/layers/LayerWindow.cpp
- artpaint/paintwindow/ImageView.cpp
- artpaint/tools/BitmapDrawer.cpp
- artpaint/tools/BrushEditor.cpp
- artpaint/tools/BrushTool.cpp
- artpaint/tools/SelectorTool.cpp
- artpaint/viewmanipulators/CropManipulator.cpp
- artpaint/viewmanipulators/FlipManipulator.cpp
> Various: cleaned up a memory leak and a bunch of dead assignments

- artpaint/application/Selection.cpp
Per the definition of how erode/shrink works, the edges of an image *should* get removed - so shrinking a "select all" selection is correct. 
Fixes #336
> Selection: rewrote Erode to be true "erode" instead of invert + dilate

- artpaint/application/HSPolygon.cpp
- artpaint/application/Selection.cpp
- artpaint/application/Selection.h
- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/PaintWindow.cpp
- artpaint/viewmanipulators/ScaleManipulator.cpp
- artpaint/viewmanipulators/ScaleManipulator.h
at long last, I *think* this works in every case.  The code isn't as pretty as I'd like but I think it works and so here we go.
- caveat, I did contract covid-19 yesterday and so my brain is either free of its normal restrictions, or completely off.  
Fixes the hardest part of #156 
hopefully nothing else broke along the way
> ScaleManipulator: add ability to scale selections

- artpaint/paintwindow/ImageView.cpp
...as the title says, I believe I have manipulator GUIs drawing outside canvas - Crop is the only one I think that really does anything at the moment.  Note that it's not *selections* but just manipulators.  
Selections might be really hard to do, and I'm not quite sure it's useful anyway?  
Anyway please give this a try when you have a chance and let me know if you see any problems:
> ImageView: draw manipulator GUIs outside the bounds of the image

- artpaint/paintwindow/PaintWindow.cpp
as discussed, these options feel superfluous.
> PaintWindow: remove Rotate +-90 menu items from Edit menu

- artpaint/paintwindow/ImageView.cpp
> ImageView: Press ESC to cancel manipulators.

- artpaint/paintwindow/ImageView.cpp
- artpaint/viewmanipulators/CropManipulator.cpp
- artpaint/viewmanipulators/ScaleCanvasManipulator.cpp
- artpaint/viewmanipulators/ScaleCanvasManipulator.h
- draws a box with 'grabbers' around the canvas
- allows scaling in any direction
- SHIFT locks aspect
- fixed minor typo in CropManip
- fixed redrawing of background when Cancel is selected
Fixes #416 
Fixes #434
> ScaleCanvasManipulator: make canvas Resize work like Crop

- artpaint/application/Selection.cpp
- artpaint/viewmanipulators/ScaleManipulator.cpp
- artpaint/viewmanipulators/ScaleManipulator.h
ok, I made scaling of selections work with the bounding box with handles.
> ScaleManipulator: Added selection box with handles for Scale

- artpaint/paintwindow/ImageView.cpp
> ImageView: don't handle ESC key if mouse is in use

- artpaint/application/PixelOperations.h
- artpaint/viewmanipulators/ScaleCanvasManipulator.cpp
in preparation for/while researching different resizing algorithms, I found that I could simplify the current resizing code immensely. will try to apply the same change to the normal scale manipulator.
seems to work as well as before, but way less code.
> ScaleCanvasManipulator: greatly simplified resizing code

- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/ImageView.h
> ImageView: find closest scale index when image is loaded

- Makefile
- artpaint/Utilities/ScaleUtilities.cpp
- artpaint/Utilities/ScaleUtilities.h
- artpaint/application/PixelOperations.h
- artpaint/viewmanipulators/ScaleCanvasManipulator.cpp
- artpaint/viewmanipulators/ScaleCanvasManipulator.h
- artpaint/viewmanipulators/ScaleManipulator.cpp
- artpaint/viewmanipulators/ScaleManipulator.h
- added nearest neighbor and bicubic types to the existing bilinear
- also refactored out common code between Scale and ScaleManipulator to make it easier to make common changes like this
Fixes #417
> Scale: add different scaling methods

- artpaint/controls/ColorPalette.cpp
i.e.:
- if you drag a color to a text editor, you get a hex value
- if you drag a hex value onto the color palette, it should set the color
Fixes #257 
... I think this works as requested now
> ColorPalette: support drag/drop of text values

- artpaint/controls/ColorPalette.cpp
added support for Pe too for #257
> ColorPalette: accept B_SIMPLE_DATA as well as B_MIME_DATA message

- artpaint/tools/ColorSelectorTool.cpp
> ColorSelector: draw alpha checkers in bg of color

- artpaint/tools/ColorSelectorTool.cpp
Fixes #325 
I'm sure it would be desirable to show the sample square even when the mouse button isn't down, but that isn't the way ArtPaint works right now.  Same problem with #304 - "tools" in ArtPaint only operate at all when you press the mouse.
of course with code all things are possible... ;D
> ColorSelector: Draw a box showing the size of the color sample

- artpaint/paintwindow/ImageView.cpp
- artpaint/viewmanipulators/CropManipulator.cpp
- artpaint/viewmanipulators/CropManipulator.h
- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/RotationManipulator.h
- artpaint/viewmanipulators/ScaleCanvasManipulator.cpp
- artpaint/viewmanipulators/ScaleCanvasManipulator.h
- artpaint/viewmanipulators/ScaleManipulator.cpp
- artpaint/viewmanipulators/ScaleManipulator.h
- artpaint/viewmanipulators/TranslationManipulator.cpp
- artpaint/viewmanipulators/TranslationManipulator.h
- artpaint/viewmanipulators/WindowGUIManipulator.h
- on enter, read values of controls
Addresses #282 
I only did the main operations, no add-ons
> Manipulators: when pressing enter, execute settings in window

- artpaint/tools/FillTool.cpp
again no functional change, just refactor/cleanup
> FillTool: more cleanup/refactoring

- artpaint/tools/FillTool.cpp
Please merge #484 first, this patch depends on it.
But, I believe this fixes the gradient chaos.  I can reproduce it pretty easily before this change, and afterward I can't seem to.  
Fixes #353
> Gradient fix

- addons/AddOns/Wave/Makefile
- addons/AddOns/Wave/Wave.cpp
- addons/AddOns/Wave/Wave.h
> Wave add-on: Add X and Y spinners for position

- artpaint/paintwindow/PaintWindow.cpp
- artpaint/paintwindow/StatusView.cpp
- artpaint/paintwindow/StatusView.h
- artpaint/tools/Brush.cpp
- artpaint/tools/Brush.h
- artpaint/tools/BrushEditor.cpp
- artpaint/tools/BrushTool.cpp
- artpaint/tools/DrawingTool.cpp
- artpaint/tools/FreeLineTool.cpp
- artpaint/tools/FreeLineTool.h
- artpaint/tools/ToolManager.cpp
- artpaint/tools/ToolSelectionWindow.cpp
- artpaint/tools/ToolSetupWindow.cpp
- artpaint/tools/Tools.h
- artpaint/windows/BrushStoreWindow.cpp
- artpaint/windows/BrushStoreWindow.h
- fix/wire up brush preview in status bar
- remove brush tool
- add option to use current brush in freehand tool
part of #202
EDIT: also realized I should gray out the "Size" slider when "Use current brush" is selected.
> BrushStore: move brush editor from Brush tool settings to store window

- artpaint/tools/EraserTool.cpp
- artpaint/tools/EraserTool.h
- artpaint/tools/FreeLineTool.cpp
- artpaint/tools/FreeLineTool.h
- also updated FreeLine tool to disable size slider when "use current brush" is checked.
More for #202 
still to-do is straight line, blur, transparency
> EraserTool: added "use current brush" functionality

- artpaint/Utilities/BitmapUtilities.cpp
- artpaint/tools/StraightLineTool.cpp
- artpaint/tools/StraightLineTool.h
also made line drawing "live" so you can see the actual line as you draw it with the appropriate color (or brush).  There can be a slight artifact sometimes with the "adjustable width" option
> StraightLineTool: added "use current brush" option

- artpaint/tools/TransparencyTool.cpp
- artpaint/tools/TransparencyTool.h
> Transparency Tool: added "use current brush" function

- artpaint/tools/FreeLineTool.cpp
- artpaint/tools/FreeLineTool.h
Fixes #222 
tablet support will be a later thing...
> FreeLineTool: added pressure setting to control opacity

- artpaint/tools/EraserTool.cpp
- artpaint/tools/EraserTool.h
Blur tool was giving me fits so I took a break to do this.
Fixes #176 
(this was the last piece to close out that ticket)
> Eraser Tool: added "Pressure" slider to control opacity of erasure

- artpaint/tools/StraightLineTool.cpp
- artpaint/tools/StraightLineTool.h
...and one more with a Pressure option.  Not sure what else will need pressure...maybe Hairy Brush?
> StraightLineTool: add pressure setting for opacity control

- artpaint/tools/Brush.cpp
- artpaint/tools/ToolButton.cpp
- artpaint/windows/BrushStoreWindow.cpp
also fixed redrawing, and cleaned up the code a tiny bit
Fixes #503
> BrushStoreWindow: make blue selection outline thicker

- artpaint/Utilities/BitmapUtilities.cpp
- artpaint/Utilities/BitmapUtilities.h
- artpaint/application/Selection.cpp
- artpaint/application/Selection.h
- artpaint/application/UtilityClasses.cpp
- artpaint/application/UtilityClasses.h
- factored out rasterization so that it's more generic and could possibly be used elsewhere.
- moved PointContainer class to UtilityClasses
- added "GetPixel" functions to BitmapUtilities to get the value of a pixel in any bitmap (only supports GRAY8 and RGBA32 for now)
> Selection: Moore's neighborhood walk replacement for SimplifySelection

- artpaint/paintwindow/ImageView.cpp
> ImageView: unhide selection when selection is cleared

- artpaint/tools/ColorSelectorTool.cpp
- also change color palette on single click
Fixes #253
> ColorSelectorTool: don't change color palette until mouse up

- artpaint/tools/AirBrushTool.cpp
- artpaint/tools/BlurTool.cpp
- artpaint/tools/BrushTool.cpp
- artpaint/tools/ColorSelectorTool.cpp
- artpaint/tools/DrawingTool.cpp
- artpaint/tools/DrawingTool.h
- artpaint/tools/EllipseTool.cpp
- artpaint/tools/EraserTool.cpp
- artpaint/tools/FillTool.cpp
- artpaint/tools/FreeLineTool.cpp
- artpaint/tools/HairyBrushTool.cpp
- artpaint/tools/RectangleTool.cpp
- artpaint/tools/SelectorTool.cpp
- artpaint/tools/StraightLineTool.cpp
- artpaint/tools/TextTool.cpp
- artpaint/tools/ToolButton.cpp
- artpaint/tools/ToolButton.h
- artpaint/tools/ToolSelectionWindow.cpp
- artpaint/tools/TransparencyTool.cpp
It's nice to have a hint to the shortcuts in the GUI, and not just the documentation.
> Add tool shortcut to ToolButton tool tip

- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/ImageView.h
- artpaint/tools/AirBrushTool.cpp
- artpaint/tools/AirBrushTool.h
- artpaint/tools/TransparencyTool.cpp
- artpaint/tools/TransparencyTool.h
per discussion in #535, draw the brush cursor on mouseup.
I think it does look better - lmk
> ImageView: draw brush cursor on MouseUp

- artpaint/tools/FillTool.cpp
- artpaint/tools/FillTool.h
> FillTool: Added "Conic" gradient type

- artpaint/layers/Layer.cpp
I believe this should fix #544 
...but I don't have a 32-bit version to test
> Layer: change 64-bit ints to unsigned long for 32-bit compatibility

- artpaint/application/PixelOperations.h
- artpaint/layers/LayerWindow.h
this should fix the catkeys for addons
> PixelOperations: moved blend mode strings to LayerWindow.h

- artpaint/tools/FillTool.cpp
- also fixed a couple of points where the gradient would flip incorrectly at perfectly horizontal or vertical angles
... note that I didn't update the help string because I don't want to annoy the translators...
> FillTool: add ability to snap angle with SHIFT to 22.5 degree increments

- artpaint/tools/FillTool.cpp
> FillTool: properly account for scale when snapping graident angles

- artpaint/controls/ColorPalette.cpp
- locales/en.catkeys
> ColorPalette: disambiguate "Colors" for translation

- artpaint/paintwindow/MagnificationView.cpp
- artpaint/paintwindow/MagnificationView.h
- artpaint/paintwindow/PaintWindow.cpp
Also refactor the zoom sub-menu generation logic.
> Use BNumberFormat for percentage values

- artpaint/tools/StraightLineTool.cpp
> StraightLineTool: set updated rect so undo works

- artpaint/Utilities/ColorUtilities.h
- artpaint/application/PixelOperations.h
- artpaint/layers/LayerWindow.cpp
- artpaint/layers/LayerWindow.h
-as a side effect, added hsl2rgb and rgb2hsl functions to ColorUtilities.h
Fixes #555
> LayerWindow: added color blend modes: Hue, Saturation, Luminosity, Color

- artpaint/viewmanipulators/WindowGUIManipulator.cpp
- artpaint/viewmanipulators/WindowGUIManipulator.h
need to re-add this function after #613
> WindowGUIManipulator: restore MessageReceived virtual function

- artpaint/application/IntelligentPathFinder.cpp
- artpaint/controls/ColorPalette.cpp
- artpaint/controls/RGBColorControl.cpp
- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/ImageView.cpp
- artpaint/tools/AirBrushTool.cpp
- artpaint/tools/BitmapDrawer.cpp
- artpaint/tools/Brush.cpp
- artpaint/tools/ColorSelectorTool.cpp
- artpaint/tools/EllipseTool.cpp
- artpaint/tools/EraserTool.cpp
- artpaint/tools/FillTool.cpp
- artpaint/tools/StraightLineTool.cpp
- artpaint/tools/TransparencyTool.cpp
- artpaint/viewmanipulators/CropManipulator.cpp
- artpaint/viewmanipulators/ScaleCanvasManipulator.cpp
- artpaint/viewmanipulators/ScaleManipulator.cpp
- artpaint/windows/BrushStoreWindow.cpp
- fixed several memory leaks
- fixed bad deallocator
- fixed undefined values
- fixed NULL pointer accesses
- removed dead initialization
Related to #124
> Clang fixes for 9/2023

- build.sh
As recommended in https://dev.haiku-os.org/ticket/18590
> Add -gdwarf-3 to COMPILER_FLAGS for debug builds

- artpaint/Utilities/BitmapUtilities.cpp
- artpaint/paintwindow/PaintWindow.cpp
- artpaint/tools/EllipseTool.cpp
- artpaint/tools/EraserTool.cpp
- artpaint/tools/RectangleTool.cpp
- artpaint/tools/StraightLineTool.cpp
- artpaint/viewmanipulators/ScaleManipulator.cpp
- artpaint/windows/ManipulatorWindow.cpp
> Clang static analysis: Fixed possible memory leaks and dead inits

- artpaint/tools/EllipseTool.cpp
> EllipseTool: fix to remove initial rotation

- artpaint/viewmanipulators/ScaleManipulator.cpp
> ScaleManipulator: return *copy* of preview bitmap if dimensions don't change

- addons/AddOns/ColorReducer/color_mapper.cpp
Fixes #614 
...as far as I can tell
> ColorReducer: fixed math for "preserve solids fs" dithering

- artpaint/tools/AirBrushTool.cpp
The `master` version of Airbrush doesn't work well with the alpha areas of selections, but this version does, and the code is simpler.
I tried a lot of back and forth and I *think* it looks about the same as before - hard to tell.
> AirbrushTool: simplify code for Spray; make it work with alpha selections
