HaikuArchives/ArtPaint

- artpaint/paintwindow/PaintWindow.cpp
The compiler can't catch this error, not even a warning.
> fix Issue #49

- artpaint/layers/Layer.cpp
- artpaint/layers/LayerWindow.cpp
- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/ImageView.cpp
- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/SysInfoBeOS.h
- artpaint/viewmanipulators/TranslationManipulator.cpp
I merged my previous branch that fixed dynamic display to master, and corrected RGB32 bitmaps to RGBA32, so that transparency in an image is preserved (for PNG etc) when it is saved.  Also now preserves the transparency of a loaded image.  COrrected a badly-placed semaphore that allowed a race-condition crash when the Layer Window was closed.
> Restored transparency of saved and loaded image files and other fixes

- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/SysInfoBeOS.h
- artpaint/viewmanipulators/TranslationManipulator.cpp
This fixes the problem of the image disappearing when translated or rotated, caused by the removal of cpu_clock_speed from system_info.  (Waddlesplash replaced this with a fixed value, but it was way too low.  A fixed value is not very satisfactory, anyway.)
> Fix for image disappearing while manipulated

- COMPILING
- artpaint/ArtPaint.rdef
- artpaint/controls/NumberSliderControl.cpp
- artpaint/viewmanipulators/TextManipulator.cpp
- artpaint/windows/AboutWindow.cpp
Version 2.1.2.  Made the TextTool control sliders active again, and fixed a glitch that sent a brush inactive if any of its sliders were changed.  (Both problems due to NumberSliderControl.)
> Fix to NumberSliderControl to cure brush and text problems

- Documentation/add_ons.html
- addons/AddOns/Working/AdaptiveHistogramEqualization/AHEManipulator.cpp
- addons/AddOns/Working/AntiDitherer/AntiDitherer.cpp
- addons/AddOns/Working/BlurAddOn/Blur.cpp
- addons/AddOns/Working/Brightness/Brightness.cpp
- addons/AddOns/Working/ColorBalanceAddOn/ColorBalance.cpp
- addons/AddOns/Working/ColorBalanceAddOn/ColorBalance.h
- addons/AddOns/Working/ColorReducer/Reducer.cpp
- addons/AddOns/Working/ColorSeparator/ColorSeparator.cpp
- addons/AddOns/Working/Contrast/Contrast.cpp
- addons/AddOns/Working/ContrastManipulatorAddOn/ContrastManipulator.cpp
- addons/AddOns/Working/DispersionAddOn/DispersionAddOn.cpp
- addons/AddOns/Working/EdgeDetector/DetectEdges.cpp
- addons/AddOns/Working/EmbossAddOn/EmbossAddOn.cpp
- addons/AddOns/Working/EnhanceEdges/EnhanceEdges.cpp
- addons/AddOns/Working/GaussianBlur/GaussianBlur.cpp
- addons/AddOns/Working/Interference/Interference.cpp
- addons/AddOns/Working/Makefile
- addons/AddOns/Working/OilAddOn/OilAddOn.cpp
- addons/AddOns/Working/PolarMapper/PolarMapper.cpp
- addons/AddOns/Working/PolarMapper/PolarMapper.h
- addons/AddOns/Working/Saturation/Saturation.cpp
- addons/AddOns/Working/Sharpness/Sharpness.cpp
- addons/AddOns/Working/Threshold/Threshold.cpp
- addons/AddOns/Working/Threshold/ThresholdView.cpp
- addons/AddOns/Working/Threshold/ThresholdView.h
- addons/AddOns/Working/TwirlAddOn/Twirl.cpp
- addons/AddOns/Working/WaveAddOn/Wave.cpp
- addons/AddOns/Working/WoodRelief/Wood.cpp
* Applied some layout management to all the add-ons.
* Added hash marks to BSliders, use consistent low/high labels
where possible.
* Sentence casing add-on names.
* Improved/corrected status bar help texts. Among other things, all
add-ons work on the active layer only, so no need to point that out.
* Threshold add-on:
Fixed some drawing errors. There's still an issue when the threshold
line is dragged to the far right. For some reason the histogramBitmap
seems to be 4 pixels short. I'll have to leave that one to a real
coder...
* Renamed PerlinWood to Wood.
* Added missing Brightness add-on to the Makefile.
> Some GUI work in the add-ons

- artpaint/layers/Layer.cpp
Every image loaded into ArtPaint lost its rightmost and bottom-most pixels.  Turns out this is a bug in the BBitmap::ImportBits used in Layer.cpp.  Don't want to mess trying to compensate for the bug, so I just restored the (only slightly longer) code used in the original.
> Reverted to old bitmap import in Layer.cpp

- artpaint/viewmanipulators/CropManipulator.cpp
The Control Window for the Crop operation was rather messed up.  When a crop was initiated, it only showed '0' for all the bounds.  When it did display them, only the leftmost digits were visible -- very confusing for large images!  Fixing the first problem has cured the second...
> Fix crop window number controls

- addons/UtilityClasses/ImageProcessingLibrary.cpp
- artpaint/viewmanipulators/ScaleManipulator.cpp
Nobody seems to get Bitmap dimensions right!  I happened to be working with a power-of-2 sized image, and hit _two_ separate exceptions!  GaussianBlur and Sharpness both crashed (they use the same code), and trying to scale up x 2 did the same.  Both seem to be in Heikke's original code (but don't crash BeOS).  They are both only off-by-one accesses, and don't even trigger a Haiku exception every time.  They were a pain to track down, but I think the fixes are correct.
(In ScaleManipulator.cpp, I also changed "..._bpr" variables to "..._pxpr", because they are  not bytes-per-row, but 32-bit pixel counts.)
> Fixes for out-of-range Bitmap references

- addons/AddOns/Working/BlurAddOn/Blur.cpp
- addons/AddOns/Working/Brightness/Brightness.cpp
- addons/AddOns/Working/Contrast/Contrast.cpp
- addons/AddOns/Working/EdgeDetector/DetectEdges.cpp
- addons/AddOns/Working/EdgeDetector/DetectEdges.h
- addons/AddOns/Working/EnhanceEdges/EnhanceEdges.cpp
- addons/AddOns/Working/EnhanceEdges/EnhanceEdges.h
- addons/AddOns/Working/GaussianBlur/GaussianBlur.cpp
- addons/AddOns/Working/Interference/Interference.cpp
- addons/AddOns/Working/MarbleTexturer/Marble.cpp
- addons/AddOns/Working/MarbleTexturer/Marble.h
- addons/AddOns/Working/Saturation/Saturation.cpp
- addons/AddOns/Working/Sharpness/Sharpness.cpp
- addons/AddOns/Working/Threshold/Threshold.cpp
- addons/AddOns/Working/TwirlAddOn/Twirl.cpp
- addons/AddOns/Working/WaveAddOn/Wave.cpp
- addons/AddOns/Working/WoodRelief/Wood.cpp
- addons/AddOns/Working/WoodRelief/Wood.h
- artpaint/application/PixelOperations.h
- artpaint/layers/Layer.cpp
- artpaint/viewmanipulators/Manipulator.cpp
- artpaint/viewmanipulators/Manipulator.h
- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/TranslationManipulator.cpp
Removed reliance on "get_BeOS_system_info" and use newer "get_system_info"
call plus "get_cpu_info" to get the CPU clock speeds.
Also removed "round" function that conflicts with std::round, and
updated call to "ImportBits" to use the public API instead of a
private one.
> ArtPaint: use newer get_system_info/get_cpu_info instead of legacy BeOS call

- addons/AddOns/Working/Interference/Interference.h
- addons/AddOns/Working/TwirlAddOn/Twirl.cpp
- addons/AddOns/Working/TwirlAddOn/Twirl.h
- addons/AddOns/Working/WaveAddOn/Wave.cpp
- addons/AddOns/Working/WaveAddOn/Wave.h
- artpaint/paintwindow/Image.cpp
Change __INTEL__ and __POWERPC__ preprocessor checks to use BYTE_ORDER
== BIG_ENDIAN. This allows more generic support for architectures, and
also fixes alpha compositing issue on x86_64 (and perhaps selection
issue on x86).
Didn't change a couple of places where inline asm is used because that might still be specific to the PowerPC arch, but I changed the elif to just else so everything else besides POWERPC will just fall through.
Fixes #81
> ArtPaint: change POWERPC/INTEL defines to use BYTE_ORDER == BIG_ENDIAN

- artpaint/paintwindow/PaintWindow.cpp
Forgot to reset the small/large scroll sizes to 8.0 and 32.0 as they were prior to the resize fixes. This should be a better scrolling experience.
Fixes #106
> ArtPaint: Restore scroll speeds accidentally lost in #104

- artpaint/layers/LayerWindow.cpp
scroll bar of Layer window was set to 100 units in height; now set
the height based on the height of the list view.
I spent some time trying to re-do the Layer window via Layout API, but it was proving to be a challenge.  This was the quickest fix for the scrollbar issue now, but I will consider revisiting this window in the future. 
Fixes #99
> ArtPaint: set proper scroll bar height of Layer window

- artpaint/tools/BrushEditor.cpp
Brush tool setup window still had an ugly weird box at the top; this patch removes that
Addresses #45
> ArtPaint: remove ugly box at top of Brush tool setup window

- artpaint/paintwindow/PaintWindow.cpp
Added lock before checking if fImageSizeWindow IsHidden in both
FrameResized and FrameMoved methods of PaintWindow.  Also added
checks for fImageSizeWindow before all other calls to Lock in
case it's NULL.
Fixes #115
> ArtPaint: lock fImageSizeWindow before checking if it's hidden

- artpaint/application/PaintApplication.cpp
- artpaint/paintwindow/PaintWindow.cpp
Simply forwards the dropped refs message to the main app.
Addresses #97, though the there mentioned ideas are not completely
trivial to implement. A first step at least.
> Open dropped images/project files

- artpaint/paintwindow/ImageView.cpp
when resizing the window, subtract the width/height of the scrollbars
so that the image doesn't overlap them.
Fixes #112
> ArtPaint: subtract scrollbars from background width

- artpaint/layers/LayerWindow.cpp
Added message filter so window activates on click. Removed "accept
first click" flag so that the grabbing of scrollbar doesn't need a
second click.
Also added step values to speed up the scrolling for the scroll wheel.
Fixes #122
> Layer Window: activate on click and don't eat first click

- artpaint/layers/Layer.cpp
- artpaint/layers/Layer.h
- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/Image.h
- artpaint/paintwindow/ImageView.cpp
When importing data into a bitmap, it MUST be the same size as the
source bitmap otherwise it doesn't work, which is why pasting a
selection into a layer didn't do anything. There's an alternate form
of ImportBits that allows a data size and offset, so I used that and
passed the offset of the selection through.
Fixes #121
> ArtPaint: Fixed copy/paste with selection

- addons/AddOns/Working/BlurAddOn/Blur.cpp
Not sure why that line was ever commented-out; seems to work fine.
Fixes #89
> Blur Add-on: uncomment line so that blur happens "live"

- artpaint/paintwindow/StatusView.cpp
BCardLayout.SetVisibleItem needs a cast of the parameter to build on 32-bit Haiku
Fixes #138
> Int32 bcardlayout

- artpaint/tools/ToolSelectionWindow.cpp
The stored window size was ignored and always resized to one
tool icon column.
While true that real horizontal arrangement of the tool icons
still isn't implemented, there's no reason to keep reverting
to one-column tool icons.
Fixes #107
> Don't resize ToolSelectionWindow to default size

- artpaint/application/FilePanels.cpp
- artpaint/application/PaintApplication.cpp
- artpaint/controls/ColorPalette.cpp
- artpaint/paintwindow/PaintWindow.cpp
- locales/en.catkeys
* Move "User documentation", About, Close, Quit to new "ArtPaint" menu.
* Remove "Help" menu.
* Move "Settings" from "Window" menu.
* Add "New project" to new "ArtPaint" menu.
Leave "New project" also in "File" menu, as people may look there too,
because that's where you open project files after all, although a new
project (= new canvas) doesn't of itself need to create a project file.
* Add ellipsis to 'special windows' (Colors, Tools...) in "Window" menu.
* Make "ArtPaint" localizable.
* Update catkeys.
> Add "ArtPaint" menu

- artpaint/tools/AirBrushTool.cpp
- artpaint/tools/BrushTool.cpp
- instead of compositing on a transparent white background,
composite brush strokes on a transparent background that is the
same color as the stroke being drawn. That way there's no unexpected
color; it's just a color composited on itself.
Fixes #183
> Alpha drawing: fix halo around soft-edged brushes

- artpaint/tools/BrushTool.cpp
- artpaint/tools/FreeLineTool.cpp
Single-click to draw a dot with the brush and freehand tool now
makes sure the compositing of the stroke happens even if no stroke
is drawn.
Fixes #184
> Brush/Freehand tool: fix single-click drawing

- artpaint/application/PaintApplication.cpp
Looks like a copy/paste mistake from the localization; trying to set a label on the wrong dialog box that was NULL. 
Fixes #191
> Crash fix: fix fImageOpenPanel that shoulda been fProjectOpenPanel

- artpaint/Utilities/BitmapUtilities.cpp
- artpaint/Utilities/BitmapUtilities.h
- artpaint/application/SettingsServer.cpp
- artpaint/application/SettingsServer.h
- artpaint/layers/Layer.cpp
- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/Image.h
- artpaint/paintwindow/PaintWindow.cpp
- artpaint/paintwindow/PaintWindow.h
- artpaint/windows/GlobalSetupWindow.cpp
- artpaint/windows/GlobalSetupWindow.h
- locales/en.catkeys
Cleaned up and finished patch for alpha checker background
- Added checkerboard alpha background to main window and layer thumbnails
- Added mode to render with the white bg (needed to properly save files)
- Added settings tab to Global settings to allow different grid sizes and colors
- Updated SettingServer to check for != B_ERROR instead of B_OK - this is because
if a setting doesn't exist the check will fail, so it's impossible to add new
settings.
Fixes #63
> Alpha checker bg: Added checkerboard alpha background as seen in similar tools

- artpaint/windows/GlobalSetupWindow.cpp
- artpaint/windows/GlobalSetupWindow.h
* Rename *ControlViews to reflect their tab view labels and
move them in the same order as the tab views in te GUI.
* Use BLayoutBuilder templates everywhere.
* Use consistent inset/spacing constants instead of hardcoded values.
* Remove insets around the tab view to avoid wasting space.
* Windows tab: alpha-sort the radio-buttons
* Transparency:
- Use font size as measure for the background preview size and
colour swatches.
- Make the colour swatches a bit smaller and put them side-by-side.
- Switch rows for "Colors" and "Grid size". Looks better and
makes space for the...
- "Defaults" button on the right side
> Settings window: Layout changes

- artpaint/paintwindow/PaintWindow.cpp
The menu "Insert text..." in the Layer menu does the exact same thing as
the Text tool. If it created a new layer for it first, it may have some
reason for existing in the "Layer" menu, but it doesn't.
> Layer menu: Remove "Insert text..."

- artpaint/viewmanipulators/TextManipulator.cpp
- locales/en.catkeys
Don't AddChild() the NumberSliderControls to the view or they'll
add some empty spacing at the top of the window. Instead, hide
them in the layout.
Use spacing constants instead of hardcoded values.
> TextManipulator: Fix layout

- artpaint/tools/Brush.cpp
- artpaint/tools/BrushTool.cpp
The function call to brush->GetData returns NULL if the dx and dy are out of range.  The code checks if the spans returned are NULL, but never checks if the brush_matrix is NULL.  Also set spans to NULL when returning NULL from Brush::GetData()
Fixes #212
> Brush Tool: check for NULL brush_matrix in draw_brush function

- artpaint/paintwindow/PaintWindow.cpp
Fix build issue for 2.3.0 32-bit build...
...but what's different about the 64-bit build?  Is it more permissive?
> Build fix: set template arguments for std::pair

- ReadMe.md
- build.sh
Adding 'targets' for:
main	:	Builds only the main app and moves it in the "dist" folder
addons	:	Builds only all addons and copies them in the "dist" folder
all		:	Builds main app and addons and puts them and the docs in the "dist" folder
clean	:	Removes all objects (main app and addons)
catkeys	:	Generates en.catkeys (main app and addons)
No argument assumes the target "all". Additional parameters are passed on to the
Makefiles, as before.
> Add 'targets' to build.sh script

- artpaint/paintwindow/PaintWindow.cpp
> PaintWindow: make sure "create canvas" window stays hidden on save.

- addons/AddOns/AntiDitherer/locales/pt.catkeys
Portugese catkeys file had blank lines that were causing a "Bad data" error during build.
> AntiDitherer addon: Deleted blank lines in pt.catkeys

- build.sh
In case someone reverted back to when there was an addons/Working folder,
remove it on "clean".
Fixes #248
> build.sh: clean out old AddOns/Working folder

- artpaint/tools/ToolButton.cpp
Added border around selected tool using ui color B_KEYBOARD_NAVIGATION_COLOR - I tried different UI colors and this seemed the best compromise between visibility and obtrusiveness,  B_WINDOW_TAB_COLOR was too much, B_MENU_SELECTED_BACKGROUND_COLOR was still a bit subtle.  
Fixes #33
> ToolWindow: add stroke to selected tool button to make it more obvious

- artpaint/controls/CMYColorControl.h
- artpaint/controls/ColorPalette.cpp
- artpaint/controls/ColorPalette.h
Added text control below color well in color palette window. Accepts:
- with or without '#'
- 3 digits, like html - assumes alpha of FF -- '123' -> '#112233FF'
- 4 digits, as above but with alpha -- '1234' -> '#11223344'
- 6 digits - assumes alpha of FF -- '123456' -> '#123456FF'
- 8 digits -- '12345678' -> '#12345678'
One caveat: setting the hex color via text does NOT update the selected color in the main window.  The problem is that ArtPaint uses whichever button was used to click on the wells and sliders to decide whether to update the fg or bg color, and in this case we have no button information.  I didn't want to assume that the user always wants to edit the fg color. After you type in (or copy/paste) a hex value, you can either right- or left-click on the palette entry.  
Fixes …
> ColorPalette: add hex color field

- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/TranslationManipulator.cpp
Translation before this change; note how the transparent portion of the selection occludes the image:
Translation after this change; note how the transparent portion of the selection is respected:
Rotation before this change; again the transparent portion of the selection is occluding the image:
Rotation after this change; transparency of the selection is respected:
Also cleaned up the code style for TranslationManipulator and RotationManipulator a bit.
Fixes #120
> Alpha selection fix: Render transparent selections properly when transforming

- artpaint/paintwindow/StatusView.cpp
- artpaint/tools/AirBrushTool.cpp
- artpaint/tools/BlurTool.cpp
- artpaint/tools/BrushTool.cpp
- artpaint/tools/ColorSelectorTool.cpp
- artpaint/tools/EllipseTool.cpp
- artpaint/tools/EraserTool.cpp
- artpaint/tools/FillTool.cpp
- artpaint/tools/FreeLineTool.cpp
- artpaint/tools/HairyBrushTool.cpp
- artpaint/tools/RectangleTool.cpp
- artpaint/tools/SelectorTool.cpp
- artpaint/tools/StraightLineTool.cpp
- artpaint/tools/TransparencyTool.cpp
- locales/en.catkeys
The help texts of the tools didn't give much insight, most just saying "Click to use %tool%"...
Now we only show the name of the currently selected tool and only add useful hints, e.g. changed behaviour with modifier keys (which we may have more of in the future).
> Minor GUI string changes

- artpaint/controls/CMYColorControl.cpp
- artpaint/controls/CMYColorControl.h
- artpaint/controls/ColorFloatSlider.cpp
- artpaint/controls/ColorPalette.cpp
- artpaint/controls/FloatControl.cpp
- artpaint/controls/FloatSliderControl.cpp
- artpaint/controls/FloatSliderControl.h
- artpaint/controls/HSVColorControl.cpp
- artpaint/controls/MultichannelColorControl.cpp
- artpaint/controls/MultichannelColorControl.h
- artpaint/controls/NumberControl.cpp
- artpaint/controls/NumberSliderControl.cpp
- artpaint/controls/NumberSliderControl.h
- artpaint/controls/RGBColorControl.cpp
- artpaint/controls/RGBColorControl.h
- decreased size/distance between controls for Color Palette window
- set max width of number controls to be maxBytes * stringwidth of a character
Not sure how much it helped- I tried to trim down the controls and I successfully shrank the text controls - this had the side effect of shrinking them throughout the app, but I looked around and mostly they look fine - except maybe the "canvas size" window.
Unfortunately I can't really shrink the hex value field...the widest value is #DDDDDDDD, and unfortunately most color values are far narrower than #DDDDDDDD, but in order to accommodate that color the field needs to be that wide.
Also, to make the arrow buttons not disappear, I had to make them a tiny bit wider.
Can't seem to get the sliders to shrink more.  The more I think I know about …
> Color Palette/Number controls: trimmed the fat

- artpaint/windows/GlobalSetupWindow.cpp
Feels a bit arbitrary, but it works.
Fixes #230
> Global Settings: use width of localized "Grid size" string to set minimum window size

- artpaint/windows/GlobalSetupWindow.cpp
Ok, the cursor setting problem was the silliest thing - the messages were opposite of the buttons!  So if you clicked "tool cursor" in the code it selected cross-hair mode, and vice versa.  That's why it didn't seem to ever work.  Now it works, you can choose cursor modes.  
possible improvements: 
- seems like the cursor stays as the finger pointer unless you leave the canvas and return. It'd be nice if it updated whenever you're on the canvas. Some kind of refresh issue?
- maybe my eyes are getting older but I find the cursors hard to see on the alpha checkerboard, even when I tried different colors. Maybe they can be made 2 pixels thick instead of 1?  
I also removed the quit confirm while in there.  I agree it's pretty useless.
Fixes #132 
Fixes #133
> GlobalSettings: fix messages for cursor settings and remove quit confirm

- artpaint/controls/FloatControl.cpp
- artpaint/controls/FloatControl.h
- artpaint/controls/NumberControl.cpp
- artpaint/controls/NumberControl.h
- artpaint/windows/GlobalSetupWindow.cpp
Adjusted size of text control in Transparency settings to space out color swatches
- added method 'SetWidthInBytes' to NumberControl and FloatControl to allow adjustments of layouts.
Fixes #274
> Transparency Settings: Adjust size of text control to space out color wells

- artpaint/viewmanipulators/CropManipulator.cpp
- artpaint/viewmanipulators/CropManipulator.h
- artpaint/windows/ManipulatorWindow.cpp
Cleaned up code for Crop manipulator, and added some new features:
- dragging a corner of the crop box maintains the aspect ratio
- shade area to be cropped
- added "use selection" button that sets the crop rectangle to the bounds of the current selection
- added "reset" button that resets the crop rectangle to the full image bounds
Fixes #39 
C&C welcome with respect to wording and UI layout.  Note that the manipulator window is a predefined layout with the Ok and Cancel at the bottom so the Reset and Use Selection buttons can't be moved down to the bottom.
I know in Photoshop, "Crop To Selection" does an instant crop but this was easier to implement and felt more flexible?
> Crop manipulator: code cleanup, added shaded area, other features

- artpaint/application/MessageConstants.h
- artpaint/application/Selection.cpp
- artpaint/application/Selection.h
- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/PaintWindow.cpp
Here's the ALT+A to select the entire canvas.  Haven't decided what to do about the "select all non-transparent pixels" yet as that's an awfully long menu item. :smile: 
Fixes #154
> Select-all: add 'select all' function to select entire canvas

- artpaint/tools/SelectorTool.cpp
- removed yellow color for intelligent scissors
- removed pen width of 2 for intelligent scissors
- changed all other types to use dashed black/white drawing color
Fixes #308 
Fixes #307
> SelectorTool: change selection drawing colors to black/white dashes

- artpaint/tools/SelectorTool.cpp
> Selector Tool: Ensure initial point for intelligent scissors is within canvas

- artpaint/paintwindow/ImageView.cpp
- artpaint/tools/EllipseTool.cpp
- artpaint/tools/RectangleTool.cpp
- locales/en.catkeys
- SHIFT maintains "square" aspect ratio
- ALT uses center-to-corner mode
- removed radio buttons for modes; added to help string
- also draw with current fg color instead of just black
Part of #126
> Ellipse/Rectangle: Use modifiers for SHIFT and ALT instead of modes

- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/PaintWindow.cpp
- locales/en.catkeys
* Always bothered me: "Clear layer" and "Clear canvas" removes all pixels, "Clear selection" only unselects all. Make it clear: "Select none" as the opposite of "Select all"
* Re-arrange the "Selection" menu items.
* Shorten "Clear layer" and "Clear canvas" to simply "Clear" as they are already in the appropriately named menus.
* Fix menu item names in comments refering to "Edit" that were moved to "Selection".
* Update en.catkeys.
> Minor string changes

- artpaint/application/Selection.h
After a lot of digging and refactoring and rewriting it turns out the issue is simply that freehand selections have antialiased edges and the not-solid-white edge pixels aren't detected.
Fixes #286
> Selection: include any non-zero pixel in selection

- artpaint/tools/SelectorTool.cpp
> Selector Tool: check bounds for spans to make sure they're valid

- artpaint/paintwindow/ImageView.cpp
Apparently the undo message for 'All non-transparent' said 'Grow selection' ... copy/paste error, oops.
> ImageView: fix undo message for 'select all non-transparent'

- artpaint/application/PixelOperations.h
- was changing 0 alpha to 1 to avoid div-by-zero errors, but the effect was returning an alpha of 1, so it was not really transparent (but 1/255 is pretty darn invisible)!
> PixelOperations: if resulting alpha is 0, just return 0 for pixel value

- artpaint/application/Selection.cpp
Added a check to prevent runaway selections - seems to happen on "all non-transparent" sometimes.
> Selection: make sure pixel in SimplifySelection stays in bounds

- artpaint/application/MessageConstants.h
- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/PaintWindow.cpp
- moved Layer->Clear to Edit->Delete as it's more accurate
- this also fixes Edit->Cut
I tried to use a shortcut but all menu shortcuts HAVE to start with ALT, and also with B_DELETE and B_BACKSPACE, nothing shows up in the menu shortcut, so it looks weird to just show "ALT" when the shortcut is "ALT+DEL"  - so I left it with no shortcut for now.
Fixes #354
> ImageView: clearing layer, selection, or canvas should clear it

- artpaint/application/UtilityClasses.cpp
- artpaint/application/UtilityClasses.h
- artpaint/viewmanipulators/RotationManipulator.cpp
...also (by necessity) updated SnapToAngle() function to allow different max angles rather than just 90
Point of note, the angle values in the manipulator dialog might seem strange but they are strange even without snapping.  I don't know how much it matters as you can always type in a specific angle if you wish, and the visual is what's really most important.  
Fixes #330 
Fixes #126
> RotationManipulator: added SHIFT to snap to 22.5 degree angles

- artpaint/tools/SelectorTool.cpp
Zero out bitmap before drawing into it - feels obvious now!
Fixes #382
> SelectorTool: make sure to clear bitmap for ellipse selections

- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/RotationManipulator.h
> RotationManipulator: when selection is set, set origin to center point

- artpaint/paintwindow/ImageView.cpp
- artpaint/viewmanipulators/TextManipulator.cpp
- also fixed setting selection for manipulator (aka TextManipulator didn't respect selection after the big selection refactor, but now it does again)
Fixes #390
> TextManipulator: add better/safer checking for selection existence

- artpaint/paintwindow/ImageView.cpp
When a manipulator is active (includes Add-Ons), and another manipulator is started, the previous behavior was to execute the changes of the active manipulator. This new behavior cancels the previous manipulator before starting the new manipulator. For example, if a user chooses "translate" and begins moving a selection, and then chooses "rotate", the previous behavior acted as if "Ok" was clicked, and now it acts as if "Cancel" was clicked.
Part of #282
> ImageView: properly cancel manipulators when interrupted

- artpaint/tools/ToolSelectionWindow.cpp
> ToolSelectionWindow: clean up tools and view when window is destroyed

- artpaint/paintwindow/PaintWindow.cpp
- also hide window when image is opened.
Fixes #344
> PaintWindow: quit canvas size window when closing paintwindow

- artpaint/paintwindow/ImageView.cpp
...only works when the canvas is active for safety reasons...I wouldn't want a spurious delete causing havoc.
Fixes #402
> ImageView: If delete key is pressed, delete selection or layer

- artpaint/paintwindow/ImageView.cpp
Fixes #421 
... well, this prevents unwanted magic wand selections, and getting into a bad state with the intelligent scissors. 
However, note that it's not possible to pan *while* you are making an 'intelligent scissors' selection. The reason is because only one operation can "own" the mouse at a time, and so once you start a selection, you can't interrupt it to pan. It's like if you are drawing a selection rectangle and you try to pan, it won't work.
> ImageView: don't send mouse click through when panning.

- artpaint/application/FilePanels.cpp
- moved format box down and put filename box back in line with buttons
- made filename box resize based on placement of settings button
Fixes #217
> FilePanel: rearrange save dialog so it behaves better with large font sizes

- artpaint/paintwindow/PaintWindow.cpp
- locales/en.catkeys
Now that the canvas menu items have no shortcuts, there's no mnemonic need to share the menu label "Scale" and shortcut 'E' between Edit and Canvas menu.
To avoid confusion (e.g. in the docs or when discussing among users) it's better to go with another label for the canvas
scaling: "Resize"
> Rename canvas "Scale..." to "Resize...", update en.catkeys

- artpaint/viewmanipulators/TextManipulator.cpp
- when comparing settings for font changes, check if font Flags() are the same - even if the font itself is the same, Flags() changes need to be reacted to.
Fixes #211
> FontManipulator: make anti-alias setting "live"

- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/MagnificationView.cpp
- below 100%, zoom tries to hit exact values
- removed decimal from Zoom as it's unnecessary
- fixed mouse zoom so it'll actually hit 1600% now
- fixed bug where +/- zoom buttons were not reflective of current zoom (i.e. if the user mouse-zoomed to 150% and then hit the + button, the zoom wouldn't go to 200%, it would go to whatever the last zoom level was before mouse-zooming)
Addresses #352, maybe fixes it? You can always hit the exact % above 100 by pressing +/- to get to the next nearest zoom level
> ImageView: improve mouse zoom

- artpaint/windows/GlobalSetupWindow.cpp
- fixes non-English settings window being cutoff
Fixes #437
> GlobalSettingsWindow: restore lost change that makes window larger

- artpaint/viewmanipulators/ScaleCanvasManipulator.cpp
- artpaint/viewmanipulators/ScaleManipulator.cpp
> Scale: make sure resultant bitmap size is large enough to hold scaled content

- artpaint/viewmanipulators/CropManipulator.cpp
- also return "original" bitmap instead of NULL when crop size doesn't change. Seems to prevent occasional crash.
Fixes #425
> Crop: subtract 1 for final width/height since we added 1 to start

- artpaint/viewmanipulators/CropManipulator.cpp
- artpaint/viewmanipulators/CropManipulator.h
- removed duplicate code for moving grabbers that is shared between scale manipulators and crop
no functional change; crop should behave exactly as before.
I should probably share the drawing code between scale and crop too one of these days...
> CropManipulator: use ScaleUtilities::MoveGrabbers to save some code

- artpaint/application/PixelOperations.h
- artpaint/tools/EraserTool.cpp
This is something that's been bugging me for a while - the edge of the erased area is not anti-aliased.  This isn't just a personal preference, it's a bug fix to the compositing - now it'll work either way, if we decide to add a checkbox for antialiasing at some point.  This fix is also needed for the Eraser portion of #176, to support soft-edged erasers.
> EraserTool: Anti-alias edge of eraser

- artpaint/paintwindow/PaintWindow.cpp
> PaintWindow: gray out recent items that don't exist on disk

- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/ImageView.h
Now ENTER should work to accept manipulators even when the window isn't focused, just like ESC does for cancelling.
Another piece of #282
> ImageView: accept Enter key when manipulators aren't focused

- artpaint/layers/LayerView.cpp
when moving layers, the layer we want to swap with is either exactly 1 position above or below the layer we're moving, so don't try to find the layer via screen coordinates - just look at the layer above or below in the layout.
Fixes #473 
Layer reordering seems to work nicely with this fix. I do like how QuickLaunch works, but it uses features of BListView and reworking the layer window to use BListView is not ideal right this minute. The BListItems seem to be explicitly drawn rather than layouts, and so that would be quite different than the current LayerViews.  It might be nice to figure out a way to give some feedback while dragging but for now this fixes the egregious bugs in layer dragging as far as I can tell.
> LayerView: identify layer by layout position instead of screen coordinates

- artpaint/viewmanipulators/ScaleManipulator.cpp
> ScaleManipulator: if x or y < 0 don't try to access the bitmap

- artpaint/layers/LayerWindow.cpp
if key is pressed in layer window, activate image window and post the message to it.
Maybe fixes part of #403 ?  Only from the Layer window so far.
> LayerWindow: forward keypresses to canvas

- artpaint/Utilities/BitmapUtilities.cpp
This fixes #479, but this change should be reverted when #363 is fixed.
I figured it out. It's not a bug, it's a feature!  The "select all non-transparent" uses the layer alpha to cut out the pieces that are transparent.  In my case here, the circle is not fully opaque, and so the resulting selection map is not fully opaque. We decide if something is selected or not based on whether it's exactly 0 or not. 
we need #363 to handle this properly and so for now/this release it's safest to just make "select all non-transparent" just take any non-opaque pixel.
> BitmapUtilities: make ConvertToMask only output exactly 1 or 0 alpha

- artpaint/paintwindow/ImageView.cpp
- artpaint/tools/AirBrushTool.cpp
- artpaint/tools/BrushTool.cpp
- artpaint/tools/EllipseTool.cpp
- artpaint/tools/FillTool.cpp
- artpaint/tools/FreeLineTool.cpp
- artpaint/tools/HairyBrushTool.cpp
- artpaint/tools/RectangleTool.cpp
- artpaint/tools/StraightLineTool.cpp
In all the color-based drawing tools, right-click draws with the bg color.
No change to Blur, Transparency, Eraser, Color Selector, or Selection Tool in this commit.
This is part of #266.
> ImageView: remove context menu for right-click

- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/PaintWindow.cpp
- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/ScaleManipulator.cpp
- artpaint/viewmanipulators/TranslationManipulator.cpp
Removed ellipsis from the ReturnName() functions for the manipulators.
When there's no selection, disable the menu items!  Forgot about this in the last PR.
> Transform selections: remove ellipsis from names, disable/enable menu items

- artpaint/application/UndoEvent.cpp
- artpaint/application/UndoEvent.h
- artpaint/application/UndoQueue.cpp
- artpaint/application/UndoQueue.h
- artpaint/controls/NumberSliderControl.cpp
- artpaint/layers/Layer.cpp
- artpaint/layers/Layer.h
- artpaint/layers/LayerView.cpp
- artpaint/layers/LayerView.h
- artpaint/layers/LayerWindow.cpp
- artpaint/layers/LayerWindow.h
- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/Image.h
- artpaint/paintwindow/ImageView.cpp
- supports undo/redo of visibility, blend mode, transparency, and layer name.
Partially addresses #240 
The remaining piece from the ticket is layer re-arranging.  However, another area that should be improved is deleting a layer.  Currently all layer settings are lost when you delete and then undo.
> LayerWindow: add ability to undo/redo layer 'meta-data' changes

- artpaint/viewmanipulators/ScaleManipulator.cpp
Fixes #493 
I didn't update canvas resize, because a pure translate in that case really is nothing.
> ScaleManipulator: register undo when selection/layer is translated

- artpaint/Utilities/BitmapUtilities.cpp
- artpaint/Utilities/BitmapUtilities.h
- artpaint/application/MessageConstants.h
- artpaint/paintwindow/StatusView.cpp
- artpaint/paintwindow/StatusView.h
- artpaint/tools/Brush.cpp
- artpaint/tools/Brush.h
- artpaint/tools/BrushTool.cpp
- artpaint/tools/BrushTool.h
- artpaint/tools/ToolManager.cpp
- artpaint/tools/ToolManager.h
Make ToolManager store brush and pass it to BrushTool 
ToolManager::GetCurrentBrush() returns default brush if brush is not defined
Add composite_func option to BitmapUtilities::CompositeBitmapOnSource 
Add BrushView to StatusView in main window; commented out for now
part of #177; still a work-in-progress but wanted to push part of it.
These changes should be invisible.
> BrushTool: move drawing functions into Brush class instead of BrushTool

- artpaint/tools/StraightLineTool.cpp
until I can figure out #507, this should at least fix master's current broken resizing straight line when zooming.
> StraightLine: fix position of rotated preview line when zooming

- artpaint/tools/TransparencyTool.cpp
- artpaint/tools/TransparencyTool.h
- also changed "speed" to pressure and made it a percentage of the way to the chosen value.
addresses transparency part of #176
> Transparency Tool: use slider instead of alpha from current color

- artpaint/layers/LayerWindow.cpp
as the description says, minor tweak so scrollbar doesn't get cut off at the minimum window size.
> LayerWindow: adjust min width so that scrollbar isn't cut off.

- artpaint/tools/Brush.cpp
- artpaint/tools/Brush.h
- artpaint/windows/BrushStoreWindow.cpp
- artpaint/windows/BrushStoreWindow.h
also fixed selection of brush on deletion, as well as moving between brushes with left/right arrow keys.
fixes #502
> BrushStoreWindow: don't allow duplicate brush adding

- artpaint/tools/BrushEditor.cpp
Okay, they should be the same size now. I even tried to verify with Magnify. 
I actually made the brush preview larger rather than decreasing the size of the stored brushes, unless you feel strongly the other way.
Fixes #521
> BrushEditor: make brush preview size match brush store pane

- artpaint/tools/FillTool.cpp
- artpaint/tools/FillTool.h
- also added Radial gradient option
Alpha still doesn't work, but aside from alpha I think this is much better.  I also added Radial gradients.
...as an aside, I tried to make the "linear" and "radial" buttons as well as the "preview" checkbox disable when you turn off gradient fill, but for some reason it totally breaks the functionality?  
Anyway please try out the gradient drawing and lmk if it is more intuitive.
the related issue is #182
> FillTool: make gradient range track mouse (aka intuitive)

- artpaint/tools/FillTool.cpp
Added a line from the gradient start point to the current point as mentioned in #182 
With this I think we can close that ticket. :smile:
> FillTool: draw line from start point to end of gradient

- artpaint/tools/TransparencyTool.cpp
- a user brush can have values outside the bounds of the sqrt table, so check if we're using a brush before checking the sqrt table.
Fixes #529 
...I knew about this issue and then forgot.  Glad you caught it before the next release!
> TransparencyTool: don't check sqrt table when using current brush

- artpaint/windows/ManipulatorWindow.cpp
With B_FLOATING_APP_WINDOW_FEEL the window floats over all open project windows. So, if you for example, "Rotate" on Project1 and switch to Project2, the "Rotate" window still floats above it and may confuse the user.
B_FLOATING_SUBSET_WINDOW_FEEL will only float over the invoking project window and disappear when switching projects.
> ManipulatorWindow: change window feel

- artpaint/tools/BrushEditor.cpp
fixes #546
as far as I can tell. :P
> BrushEditor: fixed math for brush ratio to properly reverse from stored value

- artpaint/controls/NumberSliderControl.cpp
- in the exponential value calculation, 1 is subtracted from the numerator and denominator, and never added back in, so the slider is 1 less than it should be.
Fixes #547
> NumberSliderControl: for proportional mode, re-add the subtracted 1

- artpaint/tools/BlurTool.cpp
- artpaint/tools/Brush.cpp
- artpaint/tools/Brush.h
- artpaint/tools/TransparencyTool.cpp
- this should make it easier to store different types of brushes and removes the need for "BrushToBitmap" function.
aka prep for #520 
I think I tested everywhere brushes are used.
> Brush: replace uint32 array with BBitmap to store brush

- artpaint/tools/Brush.cpp
> Brush: lock brush bitmap bits before trying to draw preview brush

- artpaint/controls/NumberSliderControl.cpp
finding all kinds of lil buggies... this one was introduced when I fixed the Size slider in the brush window; you can go up to 501 instead of 500!
> NumberSliderControl: make sure adjusted value doesn't exceed max range

- artpaint/paintwindow/ImageView.cpp
Fixes #570 
...but it works with ANY manipulator.  I think that's ok because I'm not sure why a user would do, say, a normal translate and then hit DEL.  But both actions are separately undoable.  I.e. if you translate and hit DEL before clicking OK, the translate happens, then the delete, and you can then undo just the delete.  
I feel like if a user does do such an action, this result is likely what they intended.
> ImageView: pressing DEL while in a manip executes manip and then deletes

- artpaint/controls/ColorFloatSlider.cpp
> ColorFloatSlider: set fMinRange and fMaxRange in SetMinMax

- artpaint/application/UndoQueue.cpp
Allow better context providing via unifying the actual string and its subsequent variable placeholder. Fixes ambiguities in languages with not necessarily the same word order as English.
> Apply better i18n to Undo-Redo text

- artpaint/paintwindow/ImageView.cpp
this is for both "Select all" and "Select all non-transparent"
Fixes #598
> ImageView: start selection drawing when select-all modes are used

- artpaint/paintwindow/Image.cpp
- artpaint/paintwindow/ImageView.cpp
This is a better fix for #240 I believe.  It fixes the undo-redo-undo-redo of deleted layers that didn't quite work before:
1. create a layer
2. rename it
3. delete it
4. undo delete layer, layer reappears with correct name
5. redo delete layer
6. undo delete layer, layer reappears with correct name <- this didn't work before this fix.  Now you can undo and redo and the layer properties come back 
Still missing from #240 is layer re-ordering, but at least I think this works better.
> ImageView/Image: Moved layer data copying to where layer structure is rebuilt

- artpaint/windows/BrushStoreWindow.cpp
> BrushStoreWindow: code cleanup, no functional changes

- artpaint/Utilities/BitmapUtilities.cpp
- "holes" in selections should have reversed the polygon winding order from clockwise to counter-clockwise. This fix properly reverses them now (and handles cases of holes-inside-of-holes-inside-of-holes too)
Fixes #571 as far as I can tell
following the steps in the ticket:
works! 
Please don't break it. :rofl:
> BitmapUtilities: Fix RasterToPolygonsMoore so that it correctly handles holes

- artpaint/paintwindow/PaintWindow.cpp
Fixes #299 
...it must have been done on purpose, but I really don't know why.
> PaintWindow: Removed B_NOT_ANCHORED_ON_ACTIVATE flag

- artpaint/Utilities/ScaleUtilities.cpp
Fixes #605 
yeah, the code was passing in a y-offset but not using it for vertical scaling. The horizontal scaling code was correct.  I think it's been broken since I added different scaling filters. oops.
> ScaleUtilities: actually *use* y offset for vertical scaling.

- artpaint/application/Selection.cpp
- artpaint/application/Selection.h
- artpaint/application/UndoEvent.cpp
- artpaint/application/UndoEvent.h
- artpaint/application/UndoQueue.cpp
- artpaint/application/UndoQueue.h
- artpaint/paintwindow/ImageView.cpp
- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/RotationManipulator.h
- artpaint/viewmanipulators/ScaleManipulator.cpp
- artpaint/viewmanipulators/ScaleManipulator.h
Another in the chain of selection changes... this change is what I needed for #597, but I ran into the other issues along the way so I had to fix them first.
Anyway, what this change does is store the selection *bitmap* for undo and redo operations.  Previously the selection outlines were stored, not the bitmaps.  Using the bitmaps means we can store the grayscale (aka alpha) values for selections instead of just the shapes.  When blurred or painted selections are available, this will be critical. 
It'll use more memory but it's needed for more interesting functionality. 
I was also secretly hoping this might fix #608 and it seems to?
> Selection: store selection map for undo/redo instead of polygonal data

- artpaint/paintwindow/ImageView.cpp
Missed a spot with #598 / #599
to reproduce the problem:
1. load image
2. Select all non-transparent
3. Selection -> None (Alt + D)
4. Undo 
- note the ants don't crawl
> ImageView: make sure to restart selection drawing after undo/redo

- artpaint/tools/BitmapDrawer.cpp
Fixes #586 
(also the same line-drawing is used for rotated unfilled Rectangles and the Hairy Brush so those look better too)
> BitmapDrawer: fix Wu antialiasing alpha values in DrawHairline()

- artpaint/tools/BitmapDrawer.cpp
- artpaint/tools/BitmapDrawer.h
- artpaint/tools/EllipseTool.cpp
- artpaint/tools/EllipseTool.h
Fixes #175 
finally!
caveats:
- didn't add the "specify rotation via numerical value" mentioned in the ticket
- if you zoom *while* rotating, it's a little weird.  Rectangle has the same problem.  Solution: don't zoom while rotating. :laughing:
> EllipseTool: Added rotate-able ellipses

- artpaint/tools/Brush.cpp
- also use "ceil" instead of "floor" for rectangular brushes, and that seems to fix dimensions of square brushes.
addressed the "freehand" part of #618
> Brush: add 1 to dimension of round brushes, which fixes Freehand tool widths

- artpaint/tools/BitmapDrawer.cpp
- artpaint/tools/StraightLineTool.cpp
Addressed the "straight line" part of #618 
For some strange reason the width had 1 added to it if it was an even number?  No idea why but it seems to work fine without that.
> StraightLineTool: don't add 1 to even-numbered widths

- artpaint/Utilities/ScaleUtilities.cpp
- artpaint/Utilities/ScaleUtilities.h
- artpaint/application/PixelOperations.h
- artpaint/paintwindow/ImageView.cpp
- artpaint/viewmanipulators/GUIManipulator.h
- artpaint/viewmanipulators/RotationManipulator.cpp
- artpaint/viewmanipulators/RotationManipulator.h
- artpaint/viewmanipulators/ScaleManipulator.cpp
- artpaint/viewmanipulators/ScaleManipulator.h
- artpaint/viewmanipulators/TranslationManipulator.cpp
- artpaint/viewmanipulators/TranslationManipulator.h
Fixes #621 
Not sure how to test this one other than just making sure the translate, rotate, and scale selections work at least as well as before.
I tested with rectangle, ellipse, freehand, and "select all non-transparent pixels" selections, both on new, blank canvases and existing pngs like Walter_the_OS, with undoing and redoing and such.  
Filed #625 for the one issue I found that is also present in master before this change.
> Selection: transform selections via bitmaps, not polygons

- artpaint/application/Selection.cpp
> Selection: if bitmap for ReplaceSelection is too small, zero out the rest

- artpaint/tools/AirBrushTool.cpp
- artpaint/tools/AirBrushTool.h
- artpaint/tools/EraserTool.cpp
- artpaint/tools/EraserTool.h
- artpaint/tools/FreeLineTool.cpp
- artpaint/tools/FreeLineTool.h
- artpaint/tools/TransparencyTool.cpp
- artpaint/tools/TransparencyTool.h
... this makes all the drawing tools use one standard CoordinateReader instead of several having their own.  No user-visible change should occur; Airbrush, Freehand, Eraser, and Transparency should all behave as before.
I *think* this seems to fix #545 although I feel like I saw more brush-circle-where-drawing-starts artifacts.  Maybe that's ok for this change because it'll be more easily fixable with standardized code?
> Tools: replace coordinate reading function with CoordinateReader class

- artpaint/windows/BrushStoreWindow.cpp
- break statement was erroneously moved during The Big Cleanup, and it allowed duplicate brushes to be added to Brush window.
> BrushStoreWindow: fix broken check for duplicate brushes

- artpaint/paintwindow/Image.cpp
- artpaint/viewmanipulators/CropManipulator.cpp
- artpaint/viewmanipulators/ScaleCanvasManipulator.cpp
New fix for #552 - now you can crop to 1x1 and it's actually 1x1, and I believe other crops are accurate too. 
Also fixed Canvas->Resize since it's kind of the same thing (and had the same problem).
I didn't mess with Edit->Scale; I think it's also off by 1 but it's a lot hairier in general.
> Crop/Scale Canvas Maniplators: fixed off-by-1 errors

- artpaint/tools/DrawingTool.cpp
- artpaint/tools/EllipseTool.cpp
- artpaint/tools/EllipseTool.h
- artpaint/tools/RectangleTool.cpp
- artpaint/tools/RectangleTool.h
- artpaint/tools/Tools.h
Addresses #174 
... I'm not sure about the "Adjustable outline width" option.  Would that happen *after* rotation?  I didn't add that part for now. 
A few caveats; the preview drawing has some issues where it doesn't draw correctly, but the actual drawn shape is usually correct. For example: 
1. With large widths, a rotating rectangle gets the corners cut off, but when you click to accept it, the rectangle draws properly with no cutoff corners. 
2. With large widths and small rectangles, there's a diamond-shape drawn in the center - seems like maybe a bug with Haiku's PenSize, where if it's larger than the shape you're drawing there are artifacts?
(1) might also be weird Haiku view drawing behavior?
> Rectangle/Ellipse: Add "Outline width" slider

- artpaint/viewmanipulators/TextManipulator.cpp
- previous functionality was flexible but non-intuitive
Fixes #197 - depending on your point of view.   Removes the ability to multi-color text but IMO not a bad thing.
Fixes #229
> TextManipulator: make text use current fg color only

- artpaint/tools/ToolSetupWindow.cpp
Fixes #290 
- also did minor code move to remove extra 'if' statement
> ToolSetupWindow: move Show() to *after* window feel is set.

- artpaint/tools/AirBrushTool.cpp
- artpaint/tools/CoordinateReader.cpp
- artpaint/tools/CoordinateReader.h
- artpaint/tools/FreeLineTool.cpp
- only calculate 1/4 of the brush and draw 4 pixels at once
- use LINEAR_INTERPOLATION in the CoordinateReader to get a smoother line
- adjusted linear interpolation to only get 1/10th of the coordinates
- remove snooze
@humdingerb can you give this a try to see if it's a better Airbrush experience?  It works a lot better on my end but I'm also not seeing what you're seeing, so this is just a more general attempt to improve the Airbrush feeling.
> AirBrushTool: attempting to get a smoother, better performing Airbrush

- artpaint/layers/Layer.cpp
- artpaint/paintwindow/ImageView.cpp
Missed a spot with the "respecting alpha in selections" changes, and I expect there could be a few more spots hiding along the way - the cut/copy/delete now respects selection alpha. 
The easiest way to describe this is with some pictures - load up Walter, then make a layer with a gradient on it:
...then "Select all non-transparent" on that gradient layer and then hide that layer...
...go to the Walter layer and hit the Delete key. 
the `master` branch does this :disappointed: 
But with this change, it does this, as it should:
You can also cut/copy/paste with alphaed selections.
> Layer/ImageView: respect alpha value when cutting/copying/deleting

- artpaint/paintwindow/StatusView.cpp
- artpaint/tools/Brush.cpp
- artpaint/tools/BrushEditor.cpp
- artpaint/windows/BrushStoreWindow.cpp
Fixes #523 
(but watch out for #643 when testing, which is unrelated to this change)
> BrushEditor: size preview based on max dimension to avoid jumping

- artpaint/windows/BrushStoreWindow.cpp
> BrushStoreWindow: delay drawing until all brushes are loaded

- addons/AddOns/Threshold/Threshold.cpp
- addons/AddOns/Threshold/ThresholdView.cpp
- addons/AddOns/Threshold/ThresholdView.h
Hi, I have been looking at this project for a while and I am trying to fix some of these. This fix makes the Threshold add-on update when you drag the line in the histogram. I also fixed the drawing of the histogram. 
Fixes #93
> 93 threshold live

- artpaint/paintwindow/ImageView.cpp
- artpaint/paintwindow/PaintWindow.cpp
- artpaint/viewmanipulators/FlipManipulator.cpp
- artpaint/viewmanipulators/FlipManipulator.h
- artpaint/viewmanipulators/Manipulator.h
- artpaint/viewmanipulators/ManipulatorServer.cpp
Added manipulators in the Selection menu to flip a selection in either direction. tested on a 4k image and 8k, and with multiple layers (all layers and active layer both work)
Fixes #641
> Added manipulators to flip a selection vertically and horizontally

- artpaint/Utilities/ScaleUtilities.cpp
The code in line 22 of ScaleUtilities.cpp rounds up the height. for odd-heigth images this is needed when shrinking images otherwise there are artifacts on the bottom rows. for even-height images it can cause overflow when an image in enlarged. the fix is to only do the rounding up for odd height (but in the code it tests for even because the height is 1 less than the image size showing in the UI)
also added some locks around the code that gets the source and target bits for saftey from crashes, but that is not the reason for the crash in this case
Fixes #662
> only round up height in ScaleHorizontally when image sizes are odd numbers
